import {NextResponse} from 'next/server';
import {prisma} from '@/lib/prisma';
import {requireUser,canAccessCompany} from '@/lib/auth';

type Params={params:Promise<{id:string}>};
const statuses=['PENDING','SUBMITTED','UNDER_REVIEW','APPROVED','REVISION_REQUIRED','REJECTED','CANCELLED'] as const;
const priorities=['LOW','NORMAL','HIGH','URGENT'] as const;

async function load(id:string){return prisma.request.findUnique({where:{id},include:{company:true,personnel:true,createdBy:true}});}
export async function GET(_request:Request,{params}:Params){try{const user=await requireUser();const {id}=await params;const item=await load(id);if(!item||!canAccessCompany(user,item.companyId))return NextResponse.json({error:'Request not found.'},{status:404});return NextResponse.json(item);}catch(error){if(error instanceof Error&&error.message==='UNAUTHENTICATED')return NextResponse.json({error:'Unauthorized.'},{status:401});return NextResponse.json({error:'Unable to load request.'},{status:500});}}

export async function PUT(request:Request,{params}:Params){try{const user=await requireUser();const {id}=await params;const existing=await load(id);if(!existing||!canAccessCompany(user,existing.companyId))return NextResponse.json({error:'Request not found.'},{status:404});const b=await request.json();if(!b.title?.trim())return NextResponse.json({error:'Title is required.'},{status:400});const priority=priorities.includes(b.priority)?b.priority:'NORMAL';const requestedStatus=statuses.includes(b.status)?b.status:'PENDING';const isExpoline=user.role==='SUPER_ADMIN'||user.role==='EXPOLINE_STAFF';const status=isExpoline?requestedStatus:(requestedStatus==='PENDING'||requestedStatus==='SUBMITTED'||requestedStatus==='REVISION_REQUIRED'?requestedStatus:existing.status);const item=await prisma.request.update({where:{id},data:{title:b.title.trim(),description:b.description?.trim()||null,priority,status,dueDate:b.dueDate?new Date(b.dueDate):null},include:{company:true,personnel:true}});return NextResponse.json(item);}catch(error){if(error instanceof Error&&error.message==='UNAUTHENTICATED')return NextResponse.json({error:'Unauthorized.'},{status:401});return NextResponse.json({error:'Unable to update request.'},{status:500});}}

export async function DELETE(_request:Request,{params}:Params){try{const user=await requireUser();const {id}=await params;const existing=await load(id);if(!existing||!canAccessCompany(user,existing.companyId))return NextResponse.json({error:'Request not found.'},{status:404});if(user.role!=='SUPER_ADMIN'&&user.role!=='EXPOLINE_STAFF'&&existing.createdById!==user.id)return NextResponse.json({error:'Only the request creator or Expoline staff can delete this request.'},{status:403});await prisma.request.delete({where:{id}});return NextResponse.json({ok:true});}catch(error){if(error instanceof Error&&error.message==='UNAUTHENTICATED')return NextResponse.json({error:'Unauthorized.'},{status:401});return NextResponse.json({error:'Unable to delete request.'},{status:500});}}
